name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  client:  # id of input
    required: true
   secret:
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
